services:
  web:
    container_name: frontend
    build: ./ui-terraform-training
    ports:
      - 3000:3000

  api:
    container_name: backend
    build: ./server-terraform-training # specifying path of Dockerfile i.e current dir
    ports:
      - 3001:3001
    environment:
      - PORT=3001

  nginx:
    image: nginx:1.25.4-alpine-slim
    ports:
      - '4200:4200'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount the nginx.conf file
