services:
  frontend:
    build: ../ui-terraform-training
    ports:
      - 3000:3000

  backend:
    build: ../server-terraform-training
    ports:
      - 3001:3001
    environment:
      - PORT=3001

  nginx:
    image: nginx:1.25.4-alpine-slim
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
